apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: aHZzLnhmbENMcThjcnIzNm9uWTdBaHY1eVJGcA==
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://184.73.146.206:8200/"
      path: "roboshop-dev"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          key: "token"

